### ISSUE TITLE
Recurrent structure

### ISSUE THREAD

**Issue by RomanFoell** [alshedivat/kgp#10]
Hello

how does the recurrent structure look like for the GP-LSTM. My question is focused on the output-data y or output layer and the first input layer. Is it, that you used all the hidden layers or better their outputs for recurrence, so also the first one and/or did you also use the output y recurrent in the output layer? 

Thanks.

Roman

**Comment by RomanFoell** [comment]
Hello

I updated my first post a bit. Perhaps my question is trivial or irritating, but for me in your paper it is not clear if you use for GP-LSTM exactly the same structure as you described it equation (2) in the Recurrent models part in your paper and the stacking thing with reference to [Pascanu et al., 2013] for getting a deep version. Perhaps implicitly, but there is no sentence which says it explicitly.

So as you not answered since now, I expect that you do recurrence for all outputs unless the output data y itself. Please correct me if I am wrong.

**Comment by alshedivat** [comment]
Thanks for the question.

I don't think I fully understand it. If you are asking about the experiments done in the paper, first, it is better to ask this sort of questions over the email (it's not a library-specific issue), and second, the arXiv paper will be updated very soon where we will have a more elaborate discussion of the ways the recurrence is built. In the original version of the paper, the results were obtained for an architecture that doesn't use targets at the previous time steps to predict the future time steps (in the code this means that you call `load_data` with `use_targets=False`).

I am closing the issue. For follow up, please email.
