### ISSUE TITLE
gpml backend error

### ISSUE THREAD

**Issue by aaronkerlin** [alshedivat/kgp#2]
I get the following error when trying to run the MSGP-LSTM example (the GP-LSTM example runs fine):

Oct2PyError: Oct2Py tried to run:
"""

[dlik_dx           ] = dlik(hyp, {@meanZero}, {@covGrid, {@covSEiso}, xg}, {@likGauss}, [], X_tr, y_tr);

"""
Octave returned:
error: binary operator '*' not implemented for 'sparse matrix' by 'float matrix' operations
error: called from
    apx>@<anonymous> at line 135 column 18
    ldB2_grid>@<anonymous> at line 221 column 35
    apx>conjgrad at line 285 column 36
    apx>linsolve at line 276 column 23
    ldB2_grid>@<anonymous> at line 222 column 21
    infGaussLik at line 25 column 7
    dlikGrid at line 36 column 11
    @<anonymous> at line 1 column 20

I'm running Octave 4.2.1 with the latest statistics package.

**Comment by alshedivat** [comment]
Apparently, it's [the Octave limitation](https://savannah.gnu.org/bugs/?44315) -- to work with sparse matrices, it relies on SuiteSparse routines which for some reason do not implement single precision operations between dense and sparse matrices. But, SuiteSparse implements these operations for the double precision.

**Easy fix:** in your `~/.keras/keras.json` change `"floatx": "float32"` to `"floatx": "float64"`.
