### ISSUE TITLE
RMSE

### ISSUE THREAD

**Issue by RomanFoell** [alshedivat/kgp#5]
Hi Maruan,

in your examples you use the rmse on the standardized data-sets.
In your paper, are you using this definition as well?
I was experimenting a little bit with some data-sets in your paper and got near these rmse's just by also using the standardized data-sets.
There isn't any hint in your paper, just we are using the rmse.

Cheers Roman Foell

**Comment by alshedivat** [comment]
Yes, we standardized datasets in all experiments except the system identification data. A more elaborate description of the experimental setups will be available in the updated version of the paper that will appear on arXiv very soon.
