### ISSUE TITLE
Statistics package not installed

### ISSUE THREAD

**Issue by adityay6895** [alshedivat/kgp#7]
I am getting this error. I have all dependencies installed. What could be the problem?
![screen shot 2017-04-27 at 10 49 30 pm](https://cloud.githubusercontent.com/assets/15701251/25515849/f69c9112-2b9b-11e7-982e-f9a3f6d0a8a6.png)

**Comment by alshedivat** [comment]
To use `kgp` with Octave, you need to install the `statistics` package:
```bash
$ octave --eval "pkg install -forge -verbose io"
$ octave --eval "pkg install -forge -verbose statistics"
```
